# version: "2.24.6"
# services:
#   app:
#     build: .
#     depends_on:
#       - postgres
#     environment:
#       DATABASE_URL: postgres://user:pass@postgres:5432/db
#       NODE_ENV: development
#     ports:
#       - "3000:3000"

#   postgres:
#     image: postgres:alpine
#     environment:
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - data:/var/lib/postgresql/data

# volumes:
#   data:
